server.port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    database: POSTGRESQL
  liquibase.change-log: classpath:db/changelog-master.yml